waypoint_server:
  scale: 1
  position:
    x: 1
    y: 2
    z: 3
  euler_angles:
    x: 0
    y: 0
    z: 1.57000005
  waypoints:
    - id: registed_goal_3
      position:
        x: -20.1152382
        y: -32.8430099
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 2.95978808
    - id: registed_goal_2
      position:
        x: -2.64884758
        y: -30.9960403
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -2.53301692
    - id: registed_goal_1
      position:
        x: -0.274909973
        y: -18.9300098
        z: -3
      euler_angles:
        x: 0
        y: 0
        z: -1.78037906
    - id: registed_goal_4
      position:
        x: -27.6637402
        y: -32.8257027
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 3.07968307
    - id: registed_goal_0
      position:
        x: -0.637583733
        y: -11.6355038
        z: -3.00000381
      euler_angles:
        x: 0
        y: 0
        z: -1.83331239
    - id: 1
      position:
        x: -6.00784063
        y: 4.85771799
        z: -3
      euler_angles:
        x: -0
        y: 0
        z: -0
      properties:
        - key: stop
          value: true
        - key: goal_radius
          value: 1.000000
      connections:
        - 2
    - id: 3
      position:
        x: 3.99999905
        y: 4.99999809
        z: 6
      euler_angles:
        x: -0
        y: 0
        z: -0
      connections:
        - 1
    - id: 2
      position:
        x: 1.85762167
        y: -2.25097966
        z: -3
      euler_angles:
        x: -0
        y: -0
        z: 1.58006132
      properties:
        - key: goal_radius
          value: 1.000000
